spring:
  datasource:
    username:
    password:
    url:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
details:
  executor:
    core-pool-size:
    max-pool-size:
    queue-capacity:

kafka:
  group-id:
  topic:
    ticket:
      request:
    reply:
      request: